"""Store interfaces (D4, D10).

Thin protocols instead of a framework: FAISS/bm25s today, Qdrant or another
engine later, without touching retrieval code.
"""

from pathlib import Path
from typing import Protocol

import numpy as np


class VectorStore(Protocol):
    def add(self, ids: np.ndarray, vectors: np.ndarray) -> None: ...
    def search(self, query: np.ndarray, k: int) -> list[tuple[int, float]]: ...
    def save(self, directory: Path) -> None: ...
    def __len__(self) -> int: ...


class SparseStore(Protocol):
    def add(self, ids: list[int], token_lists: list[list[str]]) -> None: ...
    def search(self, query_tokens: list[str], k: int) -> list[tuple[int, float]]: ...
    def save(self, directory: Path) -> None: ...
    def __len__(self) -> int: ...
